Repository PEACH-BROS/lets-merge, pull requests merged in 2020-05, with the labels that each got.

#4 lets-merge-2 jacoco 설정
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#6 Feature/lets merge 5
  .travis.yml
  build.gradle
  src/main/java/com/peachbros/letsmerge/mission/domain/repository/MissionRepository.java
Labels: infra

#8 Feature/lets-merge-7 : 도메인 로직 완성
  build.gradle
  src/main/java/com/peachbros/letsmerge/LetsMergeApplication.java
  src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
  src/main/java/com/peachbros/letsmerge/matcher/model/domain/strategy/MatchStrategy.java
  src/main/java/com/peachbros/letsmerge/matcher/model/domain/strategy/ThreeMatchStrategy.java
  src/main/java/com/peachbros/letsmerge/mission/domain/model/Mission.java
  src/main/java/com/peachbros/letsmerge/mission/domain/model/State.java
  src/main/java/com/peachbros/letsmerge/mission/domain/repository/MissionRepository.java
  src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
  src/main/java/com/peachbros/letsmerge/mission/model/domain/MissionManager.java
  src/main/java/com/peachbros/letsmerge/mission/model/repository/MissionRepository.java
  src/main/java/com/peachbros/letsmerge/user/model/domain/Group.java
  src/main/java/com/peachbros/letsmerge/user/model/domain/Groups.java
  src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
  src/main/java/com/peachbros/letsmerge/user/model/domain/Users.java
  src/test/java/com/peachbros/letsmerge/LetsMergeApplicationTests.java
  src/test/java/com/peachbros/letsmerge/matcher/model/domain/MatcherTest.java
  src/test/java/com/peachbros/letsmerge/mission/model/domain/MissionManagerTest.java
  src/test/java/com/peachbros/letsmerge/mission/model/domain/MissionTest.java
  src/test/java/com/peachbros/letsmerge/user/model/domain/GroupsTest.java
  src/test/java/com/peachbros/letsmerge/user/model/domain/UserTest.java
  src/test/java/com/peachbros/letsmerge/user/model/domain/UsersTest.java
Labels: feature, refactoring
